namespace: community
name: crypto
version: 0.1.0
readme: README.md
authors: null
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies:
  ansible.netcommon: '>=0.1.0'
repository: https://github.com:ansible-collections/community.crypto
documentation: https://github.com/ansible-collection-migration/community.crypto/tree/master/docs
homepage: https://github.com:ansible-collections/community.crypto
issues: https://github.com:ansible-collections/community.crypto/issues
