namespace: community
name: crypto
version: 0.1.0
readme: README.md
authors:
  - Ansible (github.com/ansible)
description: null
license_file: COPYING
tags:
  - acme
  - certificate
  - community
  - crl
  - cryptography
  - csr
  - dhparam
  - Entrust
  - Let's Encrypt
  - luks
  - openssl
  - openssh
  - pkcs12
repository: https://github.com/ansible-collections/community.crypto
documentation: https://github.com/ansible-collection-migration/community.crypto/tree/master/docs
homepage: https://github.com/ansible-collections/community.crypto
issues: https://github.com/ansible-collections/community.crypto/issues
build_ignore:
  - 'community-crypto-*.tar.gz'
  - .gitignore
  - changelogs/.plugin-cache.yaml
