namespace: community
name: crypto
version: 1.2.0
readme: README.md
authors:
  - Ansible (github.com/ansible)
description: null
license_file: COPYING
tags:
  - acme
  - certificate
  - community
  - crl
  - cryptography
  - csr
  - dhparam
  - entrust
  - letsencrypt
  - luks
  - openssl
  - openssh
  - pkcs12
repository: https://github.com/ansible-collections/community.crypto
documentation: https://docs.ansible.com/ansible/latest/collections/community/crypto/
homepage: https://github.com/ansible-collections/community.crypto
issues: https://github.com/ansible-collections/community.crypto/issues
build_ignore:
  - 'community-crypto-*.tar.gz'
  - .gitignore
  - changelogs/.plugin-cache.yaml
