---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

trigger:
  batch: true
  branches:
    include:
      - main
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - main
      - stable-*

schedules:
  - cron: 0 9 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - main
  - cron: 0 12 * * 0
    displayName: Weekly (old stable branches)
    always: true
    branches:
      include:
        - stable-*

variables:
  - name: checkoutPath
    value: ansible_collections/community/crypto
  - name: coverageBranches
    value: main
  - name: entryPoint
    value: tests/utils/shippable/shippable.sh
  - name: fetchDepth
    value: 0

resources:
  containers:
    - container: default
      image: quay.io/ansible/azure-pipelines-test-container:8.0.0

pool: Standard

stages:
  - stage: sanity
    displayName: Sanity
    dependsOn: []
    variables:
      entryPoint: tests/utils/shippable/nox.sh
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: "2.18"
              test: ansible-test-sanity-2.18
            - name: "2.19"
              test: ansible-test-sanity-2.19

  - stage: units
    displayName: Unit tests
    dependsOn: []
    variables:
      entryPoint: tests/utils/shippable/nox.sh
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: "2.18"
              test: ansible-test-units-2.18
            - name: "2.19"
              test: ansible-test-units-2.19

  - stage: docker_2_18
    displayName: Docker ansible-core 2.18
    dependsOn: []
    variables:
      entryPoint: tests/utils/shippable/nox.sh
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: alpine320 + azp/posix/1/
              test: ansible-test-integration-2.18-alpine320-azp-posix-1
            - name: alpine320 + azp/posix/2/
              test: ansible-test-integration-2.18-alpine320-azp-posix-2
            - name: default + py3.13 + azp/generic/1/
              test: ansible-test-integration-2.18-default-3.13-azp-generic-1
            - name: default + py3.13 + azp/generic/2/
              test: ansible-test-integration-2.18-default-3.13-azp-generic-2
            - name: default + py3.8 + azp/generic/1/
              test: ansible-test-integration-2.18-default-3.8-azp-generic-1
            - name: default + py3.8 + azp/generic/2/
              test: ansible-test-integration-2.18-default-3.8-azp-generic-2
            - name: fedora40 + azp/posix/1/
              test: ansible-test-integration-2.18-fedora40-azp-posix-1
            - name: fedora40 + azp/posix/2/
              test: ansible-test-integration-2.18-fedora40-azp-posix-2
            - name: ubuntu2404 + azp/posix/1/
              test: ansible-test-integration-2.18-ubuntu2404-azp-posix-1
            - name: ubuntu2404 + azp/posix/2/
              test: ansible-test-integration-2.18-ubuntu2404-azp-posix-2

  - stage: docker_2_19
    displayName: Docker ansible-core 2.19
    dependsOn: []
    variables:
      entryPoint: tests/utils/shippable/nox.sh
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: alpine321 + azp/posix/1/
              test: ansible-test-integration-2.19-alpine321-azp-posix-1
            - name: alpine321 + azp/posix/2/
              test: ansible-test-integration-2.19-alpine321-azp-posix-2
            - name: debian-bookworm + py3.11 + azp/posix/1/
              test: ansible-test-integration-2.19-debian-bookworm-3.11-azp-posix-1
            - name: debian-bookworm + py3.11 + azp/posix/2/
              test: ansible-test-integration-2.19-debian-bookworm-3.11-azp-posix-2
            - name: debian-bullseye + py3.9 + azp/posix/1/
              test: ansible-test-integration-2.19-debian-bullseye-3.9-azp-posix-1
            - name: debian-bullseye + py3.9 + azp/posix/2/
              test: ansible-test-integration-2.19-debian-bullseye-3.9-azp-posix-2
            - name: default + py3.11 + azp/generic/1/
              test: ansible-test-integration-2.19-default-3.11-azp-generic-1
            - name: default + py3.11 + azp/generic/2/
              test: ansible-test-integration-2.19-default-3.11-azp-generic-2
            - name: default + py3.13 + azp/generic/1/
              test: ansible-test-integration-2.19-default-3.13-azp-generic-1
            - name: default + py3.13 + azp/generic/2/
              test: ansible-test-integration-2.19-default-3.13-azp-generic-2
            - name: default + py3.8 + azp/generic/1/
              test: ansible-test-integration-2.19-default-3.8-azp-generic-1
            - name: default + py3.8 + azp/generic/2/
              test: ansible-test-integration-2.19-default-3.8-azp-generic-2
            - name: fedora41 + azp/posix/1/
              test: ansible-test-integration-2.19-fedora41-azp-posix-1
            - name: fedora41 + azp/posix/2/
              test: ansible-test-integration-2.19-fedora41-azp-posix-2
            - name: ubuntu2404 + azp/posix/1/
              test: ansible-test-integration-2.19-ubuntu2404-azp-posix-1
            - name: ubuntu2404 + azp/posix/2/
              test: ansible-test-integration-2.19-ubuntu2404-azp-posix-2

  - stage: remote_2_18
    displayName: Remote ansible-core 2.18
    dependsOn: []
    variables:
      entryPoint: tests/utils/shippable/nox.sh
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: freebsd/14.1 + azp/posix/1/
              test: ansible-test-integration-2.18-freebsd-14.1-azp-posix-1
            - name: freebsd/14.1 + azp/posix/2/
              test: ansible-test-integration-2.18-freebsd-14.1-azp-posix-2
            - name: macos/14.3 + azp/posix/1/
              test: ansible-test-integration-2.18-macos-14.3-azp-posix-1
            - name: macos/14.3 + azp/posix/2/
              test: ansible-test-integration-2.18-macos-14.3-azp-posix-2

  - stage: remote_2_19
    displayName: Remote ansible-core 2.19
    dependsOn: []
    variables:
      entryPoint: tests/utils/shippable/nox.sh
    jobs:
      - template: templates/matrix.yml
        parameters:
          targets:
            - name: alpine/3.21 + azp/posix/vm/
              test: ansible-test-integration-2.19-alpine-3.21-azp-posix-vm
            - name: fedora/41 + azp/posix/vm/
              test: ansible-test-integration-2.19-fedora-41-azp-posix-vm
            - name: freebsd/13.5 + azp/posix/1/
              test: ansible-test-integration-2.19-freebsd-13.5-azp-posix-1
            - name: freebsd/13.5 + azp/posix/2/
              test: ansible-test-integration-2.19-freebsd-13.5-azp-posix-2
            - name: freebsd/14.2 + azp/posix/1/
              test: ansible-test-integration-2.19-freebsd-14.2-azp-posix-1
            - name: freebsd/14.2 + azp/posix/2/
              test: ansible-test-integration-2.19-freebsd-14.2-azp-posix-2
            - name: rhel/10.1 + azp/posix/1/
              test: ansible-test-integration-2.19-rhel-10.1-azp-posix-1
            - name: rhel/10.1 + azp/posix/2/
              test: ansible-test-integration-2.19-rhel-10.1-azp-posix-2
            - name: rhel/9.7 + azp/posix/1/
              test: ansible-test-integration-2.19-rhel-9.7-azp-posix-1
            - name: rhel/9.7 + azp/posix/2/
              test: ansible-test-integration-2.19-rhel-9.7-azp-posix-2
            - name: ubuntu/22.04 + azp/posix/vm/
              test: ansible-test-integration-2.19-ubuntu-22.04-azp-posix-vm
            - name: ubuntu/24.04 + azp/posix/vm/
              test: ansible-test-integration-2.19-ubuntu-24.04-azp-posix-vm

  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - sanity
      - units
      - docker_2_18
      - docker_2_19
      - remote_2_18
      - remote_2_19
    jobs:
      - template: templates/coverage.yml
